# Generated by Django 5.2.6 on 2026-06-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_saved_messages',
            field=models.BooleanField(default=False),
        ),
    ]
